### ISSUE TITLE
Could not pass event BlockStorageMultiPlaceEvent

### ISSUE THREAD

**Issue by mrwaked** [WolfyScript/WolfyUtilities#104]
**Describe the bug**
A few days ago I upgraded CustomCrafting and WolfyUtilities to the latest version, and somehow this strange bug started to appear. It is entirely random and when it occurs it starts spam infinitely error in the console like a lot.

**Server (please complete the following information):**
 - Server Software -> Purpur (git-Purpur-1850)
 - Minecraft version -> 1.19.2
 - Java version -> 17
 - CustomCrafting -> 4.16.3.1
 - WolfyUtilities -> 4.16.9.0

**Additional context**
Log from console when error starts appear: https://pastebin.com/raw/ibwhwgir

**Comment by WolfyScript** [comment]
Yep, I fixed this issue a few days ago in WolfyUtils v4.16.9.1.
I know the update isn't available on CF yet, because it is still under review, but you can download the latest releases here on GitHub: https://github.com/WolfyScript/WolfyUtils-Spigot/releases

**Comment by mrwaked** [comment]
Yeah, thanks. I did not know that! 😄 So it is resolved and fixed.
