### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by killer5362** [WolfyScript/WolfyUtilities#112]
**Describe the bug**
Please open my latest.log to view the error I wish to report

**To Reproduce**
1. Start server

**Server (please complete the following information):**
 - Server Software 
 This server is running Paper version git-Paper-234 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: f613437)
[latest.log](https://github.com/WolfyScript/WolfyUtilities/files/13207515/latest.log)

**Comment by WolfyScript** [comment]
That version of WolfyUtils is outdated and does not support 1.20.2.
Please update to WolfyUtils 4.16.14.1 https://modrinth.com/plugin/wolfyutils
