### ISSUE TITLE
Nms fail?

### ISSUE THREAD

**Issue by Lucandroid1** [WolfyScript/WolfyUtilities#117]
Did not detect NMS implementation for server version (v1_16_R3)! Using Fallback! This might cause issue if plugins use the NMS Utils!

**Comment by WolfyScript** [comment]
I assume you are using the latest beta version. 
In that case, I have to inform you that 1.16 support has been dropped in the beta! Future versions of WolfyUtils will require Minecraft 1.17+.

**Comment by Lucandroid1** [comment]
oh ok
 thx
