### ISSUE TITLE
Error when starting up with the plugin: ExecutableBlocks

### ISSUE THREAD

**Issue by EmanuelNorsk** [WolfyScript/WolfyUtilities#118]
When starting up the server with the plugin Executable Blocks on the latest version and the latest beta of WolfyUtilities, the following error occures: 
[text.txt](https://github.com/WolfyScript/WolfyUtilities/files/14410315/text.txt)

**To Reproduce**
You install executable blocks on your server
You install WolfyUtilities on the server
Both on the latest version/beta
Start up the server to see the error

**Expected behavior**
No errors

**Screenshot**
![image](https://github.com/WolfyScript/WolfyUtilities/assets/58894136/bb998123-97a9-4b02-ad58-ae770edb04f1)

**Server**
 - Server Software: Paper
 - Minecraft version 1.20.4
 - Java version: Java 17 (Open JDK)

**Comment by WolfyScript** [comment]
I tested it with the latest version (v4.24.2.27) of ExecutableBlocks, and there were no issues.

You may be using an older version of EB, that is no longer support by WolfyUtils.   
Try to update EB and let me know if it solves the issue.

**Comment by EmanuelNorsk** [comment]
> I tested it with the latest version (v4.24.2.27) of ExecutableBlocks, and there were no issues.
> 
> You may be using an older version of EB, that is no longer support by WolfyUtils. Try to update EB and let me know if it solves the issue.

The issue is persisting, even with the latest version. While the error does not cause the plugin to disable itself, it still generates an error in the console. So it can run, but it shouldn't generate this error. I tried everything from a clean install of the server, to updating everything.
