### ISSUE TITLE
Any plans for 1.17?

### ISSUE THREAD

**Issue by ZygZagGaming** [WolfyScript/WolfyUtilities#30]
Title

**Comment by WolfyScript** [comment]
Yes, I am working on it (See java16 branch).
Today I got it build and run on Spigot 1.17 with some exceptions. 
This update, spigot changed the way it handles nms and it still has a few issues that cause errors on runtime.
I will work on solutions in the following week (including reporting issues to spigot, if they are not yet reported). 

(Also I heard 1.17 is a bit unstable right now, so... for stable servers you should consider to wait for 1.17.1 and/or paper 1.17)

**Comment by WolfyScript** [comment]
Just released an update for WolfyUtilities to 1.17 and Java 16.

It can be found [here on SpigotMC](https://www.spigotmc.org/resources/64124/update?update=407668)
