### ISSUE TITLE
Plugin displaying the old GUI

### ISSUE THREAD

**Issue by raffel080108** [WolfyScript/WolfyUtilities#41]
**Describe the bug**
Hello, I have an issue with my plugin. I have the newest version installed on my server  (both plugins) [Screenshot 1] but I still seem to be getting the old GUI (without the brewing stand recipies) [Screenshot 2], despite the plugin displaying it being in the newest version.
I already tried deleting the plugin folders and even my world folders, but the same error seems to be still occuring.

**To Reproduce**
I do not know why this is occuring, I simply downloaded the newest CustomCrafting and WolfieUtilities plugins, put them in my plugins folder and restarted the server

**Expected behavior**
I expect the plugin to display the updated GUI that includes brewing stand recipes

**Screenshots**
https://imgur.com/a/6CoYZYT

**Server:**
 - Server Software: Paper
 - Minecraft version: 1.16.5
 - Java version: Java 16

**Comment by WolfyScript** [comment]
You need to enable those recipes in the `config.yml`.
The path would be `recipes.brewing` and set it to true.
More info here: https://github.com/WolfyScript/CustomCrafting-Wiki/wiki/Config
I might have to make it more obvious... like put it in the wiki somewhere.
