### ISSUE TITLE
Advanced Crafting table not working

### ISSUE THREAD

**Issue by raffel080108** [WolfyScript/WolfyUtilities#42]
**Describe the bug**
When I place down an advanced/elite crafting table and right-click it it simply opens the normal 3x3 crafting grid

**Expected behavior**
I would expect the advanced crafting table aka a 6x6 crafting grid to open instead of the normal 3x3 one

**Server:**
 - Server Software: Paper
 - Minecraft version: 1.16.5
 - Java version: Java 16

**Comment by WolfyScript** [comment]
This is a common misconception. 
The advanced crafting table is a vanilla style crafting table.
https://github.com/WolfyScript/CustomCrafting-Wiki/wiki/Terminology-&-Features#workstations
