### ISSUE TITLE
1.16.5 error

### ISSUE THREAD

**Issue by FireslasherCodes** [WolfyScript/WolfyUtilities#43]
Sooooooo, Java 16 Don't Support mc 1.16.5 and I wanted to use this plugin on 1.16.5. So Is There Someway To Fix It?

**Expected behaviour**
Works Perfectly

**Screenshots**

**Server (please complete the following information):**
 - Paper
 - 1.16.5
 - 11

**Additional context**

**Comment by BeepoWuff** [comment]
You should be able to grab the older 1.6.x.x versions of each plugin that support java 8 and newer from the spigot pages but I'll give you the direct links too;
CustomCrafting: https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-15-1-17-free.55883/download?version=403951
WolfyUtilities: https://www.spigotmc.org/resources/wolfyutilities-core-plugin-api-1-15-1-17.64124/download?version=400169

**Comment by WolfyScript** [comment]
Huh... I am sure that 1.16.5 works with Java 16.
I run Spigot 1.16.5 on my own server with Java 16, and it's working fine, so you might have to look into your version of Paper.
Make sure you have the latest version of Paper.

If you do have other plugins that don't work with Java 16 (for some reason), then you can follow the comment by Beepo.
