### ISSUE TITLE
Doesn't support 1.19

### ISSUE THREAD

**Issue by sunnydive** [WolfyScript/WolfyUtilities#93]
**Doesn't support 1.19**
Apparently it says it's 'not Up to Date' in the console when starting up the server.
![Untitled design (2)](https://user-images.githubusercontent.com/87953622/180182174-ee0e7686-63d0-4fac-9be9-b498e76edef2.png)

**Comment by WolfyScript** [comment]
Which version of WolfyUtilities do you have? Make sure you have the latest one!

If it still doesn't work, and you have the latest version, then please send the log of the server, so I can see what is wrong.
